# Generated by Django 5.2.3 on 2025-07-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
