# Generated by Django 5.2.3 on 2025-07-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
