# Generated by Django 5.2.3 on 2025-07-05 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MySessions.mysession'),
        ),
    ]
