# Generated by Django 5.2.3 on 2025-07-05 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySessions', '0002_vote_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='session',
        ),
        migrations.AlterField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='MySessions.mysession'),
        ),
    ]
