# Generated by Django 5.2.3 on 2025-07-07 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySessions', '0003_remove_vote_session_alter_participant_session'),
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.ForeignKey(default='common', on_delete=django.db.models.deletion.CASCADE, to='scenario.role'),
        ),
    ]
